### ISSUE TITLE
Melhoria para identificação

### ISSUE THREAD

**Issue by ferronicardoso** [jpitapeva/extensao-devops-pull-request#5]
Sugestão de melhoria para o nome, ao invés de identificar como JPCompcombr porque não levar um nome mais sugestivo.

Sugestão: AI Code Reviewer ou Smart Review

**Comment by jpitapeva** [comment]
Muito obrigado amigo, confesso que criei alguns pra aprender e foi acabando as ideias kkk, vou ver pra ajustar, obrigadoo msm

**Comment by jpitapeva** [comment]
Por hora alterei a descricao para

Revisão de PullRequests com AzureOpenAI(JPCompcombr)
